org: velvor
app: teste
service: teste
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
     id: ${param:elastic_id}
     user: ${param:elastic_user}
     pass: ${param:elastic_password}
     stage: ${opt:stage, 'dev'}

functions:
  createUser:
    handler: src/createUser.createUser
    events:
      - httpApi:
          path: /user
          method: post
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /users
          method: get
  deleteUser:  
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete       




      