org: velvor
app: teste
service: teste
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
     ELASTIC_CLOUD_ID: ${param:ELASTIC_CLOUD_ID}
     user: ${param:elastic_user}
     pwd: ${param:elastic_password}
     stage: ${sls:stage}

functions:
  createUser:
    handler: src/createUser.createUser
    events:
      - httpApi:
          path: /user
          method: post
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /users
          method: get
  deleteUser:  
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete       




      